language: node_js
node_js: stable

sudo: false

install: true  # yarn bug

addons:
  firefox: "45.0"

#apt:
#  sources:
#    - google-chrome
#  packages:
#    - google-chrome-stable
#    - google-chrome-beta

os:
  - linux

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CHROME_BIN=chromium-browser; fi  # Karma CI
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi

before_script:
  - npm install -g angular-cli
#  - npm install -g karma
  - npm install
  - ng build
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then nohup bash -c "ng serve 2>&1 &"; fi  # Protractor CI

#branches:
#  only: master

notifications:
  email: true
  webhooks:
    urls: https://webhooks.gitter.im/e/02ddb87a0ad5db2f6d43
    on_success: change
    on_failure: always
    on_start: never

cache:
  directories: node_modules

script: ng test --single-run && ng e2e
