language: node_js
node_js:
- node   # Current stable
- lts/*  # Most recent LTS version
- 12
- 11
- 10     # Explicitly include an active LTS version
- 9
- 8      # Explicitly include the maintenance LTS version
- 7
- 6

before_script:
  - npm install -g gulp-cli

addons:
  chrome: stable