language: node_js
node_js: stable

sudo: false

install: true  # yarn bug

addons:
  firefox: "45.0"

#apt:
#  sources:
#    - google-chrome
#  packages:
#    - google-chrome-stable
#    - google-chrome-beta

os:
  - linux

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CHROME_BIN=chromium-browser; fi  # Karma CI
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi

before_script:
  - npm install -g angular-cli
#  - npm install -g karma
  - npm install
  - ng build

#branches:
#  only: master

notifications:
  email: true
  webhooks:
    urls: https://webhooks.gitter.im/e/36263b81dd08962e0c30
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

cache:
  directories: node_modules

script: ng test --single-run && ng serve && ng e2e
