language: node_js
node_js: stable

sudo: false

install: true  # yarn bug

addons:
  firefox: "45.0"

#apt:
#  sources:
#    - google-chrome
#  packages:
#    - google-chrome-stable
#    - google-chrome-beta

os:
  - linux

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CHROME_BIN=chromium-browser; fi  # Karma CI
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi

before_script:
  - rm -rf node_modules && npm cache clean && npm uninstall --save angular-cli; npm uninstall -g angular-cli; npm i --save @angular/cli && npm i -g @angular/cli
  - npm install
  - npm run build.prod
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then nohup bash -c "npm run serve.prod 2>&1 &"; fi  # Protractor CI
  - cat nohup.out

#branches:
#  only: master

notifications:
  email: true
  webhooks:
    urls: https://webhooks.gitter.im/e/02ddb87a0ad5db2f6d43
    on_success: change
    on_failure: always
    on_start: never

cache:
  directories: node_modules

script: npm run tests.all
