version: '2'

services:

  igo2-dev:
    build:
      context: .
      dockerfile: ./.docker/igo2.development.dockerfile
    command: npm start
    container_name: igo2-start
    image: igo2-dev
    networks:
      - dev-network
    ports:
      - '5554:5555'

networks:
  dev-network:
    driver: bridge
