# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
#

name: Pull Request
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: The branch or tag ref that triggered the workflow run.
      run: echo ${GITHUB_REF#refs/*/}

    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 24

    - name: Install dependencies
      run: npm ci --no-audit

    - name: Security
      run: npm audit --omit dev && npm audit signatures

    - name: Quality
      run: npm run lint.check & npm run format.check

    - name: Test
      run: npm run e2e

    - name: Build
      run: npm run build.prod
